name: Publish to PyPI

on:
  push:
    # Publish when a tag is pushed
    # Expect tags like 1.2.3 (numeric versions). GitHub Actions uses glob patterns, so '*.*.*' will match.
    tags:
      - '*.*.*'
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip hatch twine

      - name: Build distributions with hatch
        run: |
          hatch build -f

      - name: Publish to PyPI (trusted)
        uses: pypa/gh-action-pypi-publish@v1.6.2
