name: Publish to PyPI

on:
  push:
    # Publish when a tag is pushed
    # Expect tags like 1.2.3 (numeric versions). GitHub Actions uses glob patterns, so '*.*.*' will match.
    tags:
      - '*.*.*'
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip hatch twine

      - name: Inject tag version into package
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Detected ref: $GITHUB_REF"
          TAG=${GITHUB_REF#refs/tags/}
          echo "Using tag version: $TAG"
          cat > src/ami_helper/__about__.py <<EOF
# SPDX-FileCopyrightText: 2025 Gordon Watts <gwatts@uw.edu>
#
# SPDX-License-Identifier: MIT
__version__ = "${TAG}"
EOF

      - name: Build distributions with hatch
        run: |
          hatch build

      - name: Publish to PyPI (trusted)
        uses: pypa/gh-action-pypi-publish@v1.6.2
